### ISSUE TITLE
Improve plugin configuration

### ISSUE THREAD

**Issue by slepic** [olvlvl/composer-attribute-collector#14]
Hello,

first of all, thank you very much for this package.

I would like to improve and extend the configuration system of the plugin.

Currently the `ignore-paths` config option treats the value as a substring of the filepath. This is undesired because it can match things that the author did not expect.

For example if I add ignored path `vendor` to apply the plugin only to project files and coincidentally I also have a source directory `src/vendor`, then the subdirectory in src is also ignored.

In my opinion, it should treat those paths as relative paths to the root of the project.

Also I would probably prefer if I could configure included paths rather than ignored paths. Or actually conjunction of both would be totally legit. Being strict is good, I would even go so far to recommend using the inclusion first approach in the docs of the package.

```
"extra": {
  "include-paths": [
    "src/"
  ],
}
```
seems better than
```
"extra": {
  "ignore-paths": [
    "tests/",
    "vendor/"
  ],
}
```

Further It could be usefull to configure a set (again both inclusion and exclusion sets) of actual attributes. It does not make sense to collect attributes that I don't care of in my app.

```
"extra": {
  "include-attributes": [
    "Doctrine\\"
  ],
}
```

All those could be implemented separately (I guesss) and I'm willing to help implementation but first I'd like to hear your option...

**Comment by olvlvl** [comment]
Hi, thanks for your suggestions. I think it's a good idea to have the path relative to the `composer.json` path, that should remove surprises. I would greatly appreciate a PR for this feature.

Regarding filtering, one of the goals while creating the plugin was to avoid configuration as much as possible. I wanted a solution that would _just_ work with minimal effort. I added the "ignore" option to be able to exclude PHP files that contain both classes and side-effect code. I'm okay to add more filters, but they need to provide tangible value e.g. reducing the collection process time by X. Collecting attributes is the least expansive part of the process, and once the static file is created unused attributes don't cost anything. So, maybe a "only-paths" could be something to explore, although it leaves the burden on the end-user.

**Comment by slepic** [comment]
Adding blacklist as well as whitelist should work that if whitelist is not provided then everything except blacklist is allowed. That way people who want minimal effort can still use ignore list only and everything should be fine. While people who want strict definition can opt in for one.

The same can be applied to range of scanned attributes. My concern here wasn't as much about  the compilation time, but rather about the size of the attributes.php file. If I have a large code base with lots of various attributes but I only have few attributes for which I lavarage this package then generating a large collection of attributes forces me to read large file to only use small part of it. Again opt in for fine grained control should not be a problem.

**Comment by olvlvl** [comment]
Hi, I'm closing this issue since v2.0.0 allows to include and exclude paths. Thanks for your contribution.
