### ISSUE TITLE
Error filemtime on nonexisting file after updating a composer package

### ISSUE THREAD

**Issue by slepic** [olvlvl/composer-attribute-collector#15]
Hello while running composer update I encountered this error.

>Generating attributes file
In MemoizeClassMapFilter.php line 51:                                                          
  filemtime(): stat failed for /app/vendor/nette/forms/src/Bridges/FormsLatte/Nodes/NNameNode.php

It seems related to caching. The source file not found existed in previous version of the updated package but not in the new one.
When i deleted the `.composer-attribute-collector` directory, the problem went away.

**Comment by olvlvl** [comment]
Thanks for reporting the issue. Indeed, I'm not checking whether the file exists before calling `filemtime()`, and it could be present in the cache but not in the filesystem. I'll look into it.
