### ISSUE TITLE
Error unserialize(): undefined constant

### ISSUE THREAD

**Issue by slepic** [olvlvl/composer-attribute-collector#19]
Added attribute using an enum constant

```php
enum SomeEnum: string
{
  case foo = 'foo';
}

#[Attribute(Attribute::TARGET_CLASS)]
class SomeAttr
{
  public function __construct(public SomeEnum $value) {}
}

#[SomeAttr(SomeEnum::foo)]
class SomeClass
{
}
```

Generate attributes filling .composer-attribute-collector cache dir.

Then remove the attribute and the constant (ie. switch to branch where they dont exist)

Try to run composer dump-autoload and you get this error

```
Generating attributes file

In FileDatastore.php line 42:
                                                                      
  unserialize(): Undefined constant SomeEnum::foo
```

Clearing the cache dir removes the problem.

**Comment by withinboredom** [comment]
> Clearing the cache dir removes the problem.

This only appears to work once, after it is generated you get the same error.

**Comment by slepic** [comment]
> > Clearing the cache dir removes the problem.
> 
> This only appears to work once, after it is generated you get the same error.

Sure, if you repeat the same steps, the problem will appear again. Or do you mean something else?

**Comment by withinboredom** [comment]
I was just adding that the workaround only works once. (I have a file watcher that crashes on error, and I had to add an `rm -rf` before it runs `composer dump` after a file change, in order to keep it running)

**Comment by slepic** [comment]
> I was just adding that the workaround only works once. (I have a file watcher that crashes on error, and I had to add an `rm -rf` before it runs `composer dump` after a file change, in order to keep it running)

Aah, right. I am not using any file watcher, but I can totally see how this error can ocurr quite frequently if you're using one. 

@olvlvl looks like the cache is quite troublesome maybe adding a config option to turn it off could be a good starting point to implement before the cache itself is improved

**Comment by olvlvl** [comment]
I'm unable to reproduce the issue. I created a branch over here, and it works as expected:

https://github.com/olvlvl/composer-attribute-collector/compare/case-enum?expand=1

@slepic Could you have a look?

**Comment by olvlvl** [comment]
@slepic Could you try this branch please? https://github.com/olvlvl/composer-attribute-collector/compare/ignore-unserialize-errors?expand=1

**Comment by slepic** [comment]
@olvlvl hmm I will check

A tried to reduce my use case to an MVP for the report, but I did that only in my head, maybe i reduced it too much and the error does not occur in that case. 

Should i try another time? Even though I can confirm in this branch (https://github.com/olvlvl/composer-attribute-collector/compare/ignore-unserialize-errors?expand=1) the error went away in my usecase. 
The "unserialize error: ..." message didnt appear anywhere though, not sure if it should have.

------------------------

Anyway while switching the package version i got this error (cache was present at the time)

```
  - Upgrading olvlvl/composer-attribute-collector (v1.2.2 => dev-ignore-unserialize-errors a27b061): Extracting archive
Generating autoload files
Generating attributes file

In MemoizeAttributeCollector.php line 62:
                         
  Undefined array key 3 
```

could that be because 1.2.2 didnt have property attributes?


I also got this while switching back to tagged version

```
In MemoizeClassMapFilter.php line 51:
                                                                                                       
  filemtime(): stat failed for /app/vendor/olvlvl/composer-attribute-collector/src/TargetProperty.php
```
which also looks like issue of downgrading to vesion without property attribute support.

is it worth inversitaging, should I file another issue?

**Comment by olvlvl** [comment]
I improved the code and added some tests, please have a look: https://github.com/olvlvl/composer-attribute-collector/pull/21

**Comment by olvlvl** [comment]
> regarding the upgrade/downgrade errors, would it be possible to clear the cache on down/upgrades? that doesnt happen often and it could be simpler than having to deal with each upgrade related error separately...

Starting with v2, the cache file includes the version of the plugin. We shouldn't have a situation where the cache file is not compatible with the plugin.
