### ISSUE TITLE
Collector shouldn't instantiate attributes

### ISSUE THREAD

**Issue by ruudk** [olvlvl/composer-attribute-collector#2]
While testing this on our project, I noticed that the Collector tries to instantiate the attribute. For performance reasons, you don't want this. Only when you need the attribute, you want to instantiate it.

The code that instantiates:

https://github.com/olvlvl/composer-attribute-collector/blob/42669a2fae2bca4da0f3078487c9216caeb06040/src/Collector.php#L49

Stacktrace:
```
In Reflector.php line 48:

  [InvalidArgumentException]
  Attribute TicketSwap\Shared\Infrastructure\GraphQL\Compiler\Attribute\GraphQL\ObjectType not found on reflection.


Exception trace:
```
 MyCustomAttributeThatThrowsForSomeReasonInTheConstructor->__construct() at n/a:n/a
 ReflectionAttribute->getArguments() at /Volumes/CS/www/symfony/vendor/olvlvl/composer-attribute-collector/src/Collector.php:49
 olvlvl\ComposerAttributeCollector\Collector->addTargetMethod() at phar:///opt/homebrew/Cellar/composer/2.5.1/bin/composer/src/Composer/Plugin/PluginManager.php(274) : eval()'d code:173
olvlvl\ComposerAttributeCollector\Plugin_composer_tmp0::collectAttributes() at phar:///opt/homebrew/Cellar/composer/2.5.1/bin/composer/src/Composer/Plugin/PluginManager.php(274) : eval()'d code:100
 olvlvl\ComposerAttributeCollector\Plugin_composer_tmp0::dump() at phar:///opt/homebrew/Cellar/composer/2.5.1/bin/composer/src/Composer/Plugin/PluginManager.php(274) : eval()'d code:81
 olvlvl\ComposerAttributeCollector\Plugin_composer_tmp0::onPostAutoloadDump() at phar:///opt/homebrew/Cellar/composer/2.5.1/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:206
```

Apparently, [`ReflectionAttribute::getAttributes()`](https://www.php.net/manual/en/reflectionattribute.getarguments.php) instantiates. This is not documented.

**Comment by ruudk** [comment]
I cannot share the code as it's private. I think you can verify it by having a custom attribute, that does a throw in the constructor. The plugin shouldn't instantiate the attribute. But it does.

**Comment by olvlvl** [comment]
The plugin needs to fetch the arguments to be able to dump the code that instantiates the attributes with their arguments. Why is the constructor throwing an exception? Is there something wrong with the arguments?

**Comment by olvlvl** [comment]
I'm clausing this issue for lack of code.
