### ISSUE TITLE
__PHP_Incomplete_Class_Name with cache

### ISSUE THREAD

**Issue by Furgas** [olvlvl/composer-attribute-collector#20]
I've encountered a problem when using attributes that have class-typed parameters. First run works OK, but consecutive runs render `__PHP_Incomplete_Class_Name` in `attributes.php` file. Clearing the cache fixes the issue for the next run. This issue occurs only, when the attribute class (or maybe the parameter class) is in a vendor package.

I've prepared a test repository showing this problem:
```
git clone https://github.com/sdoatput/attribute-collector-test
cd attribute-collector-test
./test.sh
```

**Comment by Furgas** [comment]
My "fix" for now is removing the cache with:
```
"scripts": {
	"pre-autoload-dump": "rm -rf .composer-attribute-collector"
}
```
in `composer.json`.

**Comment by olvlvl** [comment]
Hi Furgas,

Any code you could share? Like the definition of the attribute class, the rendered `attributes.php` file? Also, any idea why the class cannot be found by `unserialize()` in subsequent runs?

**Comment by Furgas** [comment]
Umm, I've prepared [the code](https://github.com/sdoatput/attribute-collector-test) specially for this issue - please look at the original post.
I have not analyzed the flow and why `unserialize` is not working when the cached is used.
