### ISSUE TITLE
Collect bare functions?

### ISSUE THREAD

**Issue by withinboredom** [olvlvl/composer-attribute-collector#29]
Does this library only collect attributes on methods, classes and properties? Is there a way to collect them on bare functions as well?

**Comment by olvlvl** [comment]
Hi, the plugin collects attributes on classes. What would be the use case for attributes on functions?

**Comment by withinboredom** [comment]
Functions are a valid target for attributes (as are properties, parameters, and constants, but those aren't as useful to look up).

In my case, I want to use it for something akin to the following on an internal framework:

```php
#[\Attribute(\Attribute::IS_REPEATABLE | \Attribute::TARGET_CLASS | \Attribute::TARGET_METHOD | \Attribute::TARGET_FUNCTION)]
class Route {
  public function __construct(public string $path) {}
}
```

Then, during startup, I can use this library to find all the classes/routes that are registered, but there is no way to search functions.

This may seem odd, because there isn't a way to autoload functions; but that is a non-issue in this codebase.

**Comment by olvlvl** [comment]
Looking up functions is way more complicated than looking up named classes because I would need to parse the abstract syntax tree to make sure a function definition is not a method of a class. Moreover, I cannot use autoloading to load them, that's another thing that would need to be created.

In your app, how do you pass services to such functions? For example, when a function needs to render rows from a database. Usually, micro-frameworks use closures for their endpoints and they have access to a DIC within their scope. If you have functions defined outside of the router, I'm curious to know how they access services.

**Comment by withinboredom** [comment]
> Looking up functions is way more complicated than looking up named classes because I would need to parse the abstract syntax tree to make sure a function definition is not a method of a class.

Interesting. Would you be open to a PR?

We are currently doing this:
```
$funcs = get_defined_functions()['user'];

// $funcs now contains all user defined functions
```

> Moreover, I cannot use autoloading to load them, that's another thing that would need to be created.

I think as long as it is documented, it is fine. For functions, it doesn't need to be autoloaded per se. For example, TargetFunction could literally just contain a string-callable.

```php
<?php

function test(string $prop) {
	echo $prop;
}

$func = 'test';

$func('Hello, World!');
```

It would be up to the developer to ensure it is loaded prior to calling it.

> In your app, how do you pass services to such functions?

PHP-DI has the ability to inspect parameters and inject them into function calls. So, if you want a repository or whatever:

```php
#[Route('GET', '/some/{thing}')]
function doSomething(MyRepository $repository, string $thing) {}
```

Would inject the repository service and `thing` from the request parameter, as an argument with the same name.

**Comment by olvlvl** [comment]
> Would you be open to a PR?

Yes, of course :)

**Comment by withinboredom** [comment]
I see what you mean now. This probably won't be possible until we get function autoloading...

**Comment by olvlvl** [comment]
I'm closing the thread for now.
