### ISSUE TITLE
Support named arguments / arguments order

### ISSUE THREAD

**Issue by xepozz** [olvlvl/composer-attribute-collector#7]
Unordered named arguments cause exception. It's better to dive into example.

Attribute:
```php
#[\Attribute(\Attribute::IS_REPEATABLE)]
class RouteAttribute
{
    public function __construct(
        public string $path,
        public ?string $name = null,
        public string|array $methods = [],
    ) {
    }
}
```
So parameters order is: 
1. Path
2. Name
3. Methods

Then let's take a look at the usage.

Class:
```php
class SiteController
{
    #[RouteAttribute(path: '/test', methods: ['GET'], name: 'site/index')]
    public function test()
    {
        // ...
    }
}
```

The dump:
```php
        \App\RouteAttribute::class => [
            [ ['/test', array (
  0 => 'GET',
), 'site/index'], \App\Controller\SiteController::class, 'test' ],
        ],
```
The order is:
1. Path
2. Methods
3. Name

It's incorrect and won't work so `php` proves it: `Caught unhandled error "App\RouteAttribute::__construct(): Argument #2 ($name) must be of type ?string, array given`
I'd suggest to generate the dump as `parameter name => value`, then the dump above will look like:
```php
        \App\RouteAttribute::class => [
            [ ['path' => '/test', 'methods' => array (
  0 => 'GET',
), 'name' => 'site/index'], \App\Controller\SiteController::class, 'test' ],
        ],
```
If you do it array unpacking in `\olvlvl\ComposerAttributeCollector\Collection::forClass` will work correctly.

**Comment by olvlvl** [comment]
Great idea, Dmitry. I gotta say I never faced this issue because I follow the prompt of the IDE to sort arguments, like a good boy :) I'll look into it.

**Comment by olvlvl** [comment]
@xepozz Could you try these changes? https://github.com/olvlvl/composer-attribute-collector/pull/8

**Comment by xepozz** [comment]
I'll try them today or tomorrow
